name: Android Check Build

on:
  push:
    branches:
      - master
      - develop
      - branch-*
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: "Build APK"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with Gradle
      uses: ./.github/actions/gradle_docker
      with:
          gradle-cmd: assembleProdRelease -PkeystorePassword=${{secrets.KEYSTORE_PASSWORD}} -PkeyAliasPassword=${{secrets.KEY_ALIAS_PASSWORD}}
    - name: Upload APK
      uses: actions/upload-artifact@v1.0.0
      with:
          name: app
          path: app/build/outputs/apk/prod/release/app-prod-release.apk
    - name: Upload Mapping File
      uses: actions/upload-artifact@v1.0.0
      with:
        name: mappingFile
        path: app/build/outputs/mapping/prodRelease/mapping.txt

  test:
    name: "Run Tests"
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        uses: reactivecircus/android-emulator-runner@5de26e4bd23bf523e8a4b7f077df8bfb8e52b50e
        with:
          api-level: 29
          script: ./gradlew connectedDevDebugAndroidTest

  sonar:
    name: "Sonar Analysis"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Sonar Analysis
      run: ./gradlew sonarqube
      env:
        SONARCLOUD_URL: "https://squad-1-core.sc-dev.io"
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ github.token }}
